div_safety_metrics = [
    "div_safety_category",
    "cash_div_payout_ratio_ttm",
    "div_payout_gaap",
    "div_payout_nongaap",
    "div_payout_nongaap_fy1",
    "cf_payout",
    "cf_payout_fy1",
    "fcf_yield_div_yield",
    "div_yield_div_payout",
    "div_coverage_ratio_fy1",
    "int_cover",
    "net_lt_debt_tot_assets",
    "net_lt_debt_ebitda",
    "debt_eq",
    "tot_debt_cap",
    "net_margin",
    "rtn_on_common_equity",
    "cash_from_operations_as_reported",
    "cash_per_share_ttm",
    "log_of_unadjusted_stock_price",
    "capm_alpha_60m",
    "institutional_ownership_level",
    "sustainable_growth_rate",
    "div_grow_rate",
    "dividend_coverage_ratio_ttm",
    "fixed_asset_turnover_ttm",
    "dps_consensus_mean_percent_revisions_down_1_annual_period_fwd",
    "net_asset_to_pension_liabilities_annual",
    "div_safety_category_avg_5y",
    "cash_div_payout_ratio_ttm_avg_5y",
    "div_payout_gaap_avg_5y",
    "div_payout_nongaap_avg_5y",
    "div_payout_nongaap_fy1_avg_5y",
    "cf_payout_avg_5y",
    "cf_payout_fy1_avg_5y",
    "fcf_yield_div_yield_avg_5y",
    "div_yield_div_payout_avg_5y",
    "div_coverage_ratio_fy1_avg_5y",
    "int_cover_avg_5y",
    "net_lt_debt_tot_assets_avg_5y",
    "net_lt_debt_ebitda_avg_5y",
    "debt_eq_avg_5y",
    "tot_debt_cap_avg_5y",
    "net_margin_avg_5y",
    "rtn_on_common_equity_avg_5y",
    "cash_from_operations_as_reported_avg_5y",
    "cash_per_share_ttm_avg_5y",
    "log_of_unadjusted_stock_price_avg_5y",
    "capm_alpha_60m_avg_5y",
    "institutional_ownership_level_avg_5y",
    "sustainable_growth_rate_avg_5y",
    "div_grow_rate_avg_5y",
    "dividend_coverage_ratio_ttm_avg_5y",
    "fixed_asset_turnover_ttm_avg_5y",
    "dps_consensus_mean_percent_revisions_down_1_annual_period_fwd_avg_5y",
    "net_asset_to_pension_liabilities_annual_avg_5y",
]

div_growth_metrics = [
    "div_growth_category",
    "dps_yoy",
    "dividend_per_share_change_dislpay",
    "dividend_lt_fwd_growth",
    "div_grow_rate3",
    "div_grow_rate5",
    "div_grow_rate10",
    "revenue_change_display",
    "eps_change_display",
    "fcf_per_share_change_display",
    "ebitda_change_display",
    "ebit_change_display",
    "return_on_net_tangible_assets",
    "log_of_unadjusted_stock_price",
    "coefficient_of_variation_90d",
    "degree_of_operating_leverage_ttm",
    "div_growth_category_avg_5y",
    "dps_yoy_avg_5y",
    "dividend_per_share_change_dislpay_avg_5y",
    "dividend_lt_fwd_growth_avg_5y",
    "div_grow_rate3_avg_5y",
    "div_grow_rate5_avg_5y",
    "div_grow_rate10_avg_5y",
    "revenue_change_display_avg_5y",
    "eps_change_display_avg_5y",
    "fcf_per_share_change_display_avg_5y",
    "ebitda_change_display_avg_5y",
    "ebit_change_display_avg_5y",
    "return_on_net_tangible_assets_avg_5y",
    "log_of_unadjusted_stock_price_avg_5y",
    "coefficient_of_variation_90d_avg_5y",
    "degree_of_operating_leverage_ttm_avg_5y",
]

div_yield_metrics = [
    "div_yield_category",
    "div_yield_4y",
    "dividend_yield",
    "div_yield_fwd",
    "yld_on_cost_1y",
    "yld_on_cost_3y",
    "yld_on_cost_5y",
    "earnings_yield",
    "earn_yield_gaap_fy1",
    "oper_income_market_cap",
    "oper_income_fy1_market_cap",
    "fcf_yield",
    "fcf_yield_fy1",
    "div_yield_category_avg_5y",
    "div_yield_4y_avg_5y",
    "dividend_yield_avg_5y",
    "div_yield_fwd_avg_5y",
    "yld_on_cost_1y_avg_5y",
    "yld_on_cost_3y_avg_5y",
    "yld_on_cost_5y_avg_5y",
    "earnings_yield_avg_5y",
    "earn_yield_gaap_fy1_avg_5y",
    "oper_income_market_cap_avg_5y",
    "oper_income_fy1_market_cap_avg_5y",
    "fcf_yield_avg_5y",
    "fcf_yield_fy1_avg_5y",
]

div_history_metrics = [
    "div_consistency_category",
    "dividend_growth",
    "dividend_consistency",
    "div_consistency_category_avg_5y",
    "dividend_growth_avg_5y",
    "dividend_consistency_avg_5y",
]

earnings_metrics = [
    "analysts_up_percent",
    "analysts_down_percent",
    "analysts_up",
    "analysts_down",
    "analysts_up_percent_avg_5y",
    "analysts_down_percent_avg_5y",
    "analysts_up_avg_5y",
    "analysts_down_avg_5y",
]

valuation_metrics = [
    "pe_nongaap",
    "pe_nongaap_fy1",
    "pe_ratio",
    "pe_gaap_fy1",
    "peg_gaap",
    "peg_nongaap_fy1",
    "ev_12m_sales_ratio",
    "ev_sales_fy1",
    "ev_ebitda",
    "ev_ebitda_fy1",
    "ev_ebit",
    "ev_ebit_fy1",
    "ps_ratio",
    "ps_ratio_fy1",
    "pb_ratio",
    "pb_fy1_ratio",
    "price_cf_ratio",
    "price_cf_ratio_fy1",
    "dividend_yield",
    "pe_nongaap_avg_5y",
    "pe_nongaap_fy1_avg_5y",
    "pe_ratio_avg_5y",
    "pe_gaap_fy1_avg_5y",
    "peg_gaap_avg_5y",
    "peg_nongaap_fy1_avg_5y",
    "ev_12m_sales_ratio_avg_5y",
    "ev_sales_fy1_avg_5y",
    "ev_ebitda_avg_5y",
    "ev_ebitda_fy1_avg_5y",
    "ev_ebit_avg_5y",
    "ev_ebit_fy1_avg_5y",
    "ps_ratio_avg_5y",
    "ps_ratio_fy1_avg_5y",
    "pb_ratio_avg_5y",
    "pb_fy1_ratio_avg_5y",
    "price_cf_ratio_avg_5y",
    "price_cf_ratio_fy1_avg_5y",
    "dividend_yield_avg_5y",
]

growth_metrics = [
    "revenue_growth",
    "revenue_change_display",
    "ebitda_yoy",
    "ebitda_change_display",
    "operating_income_ebit_yoy",
    "ebit_change_display",
    "diluted_eps_growth",
    "eps_change_display",
    "eps_ltg",
    "levered_free_cash_flow_yoy",
    "fcf_per_share_change_display",
    "op_cf_yoy",
    "cf_op_change_display",
    "roe_yoy",
    "roe_change_display",
    "working_cap_change",
    "capex_change",
    "dividend_per_share_change_dislpay",
    "dps_yoy",
    "revenue_growth_avg_5y",
    "revenue_change_display_avg_5y",
    "ebitda_yoy_avg_5y",
    "ebitda_change_display_avg_5y",
    "operating_income_ebit_yoy_avg_5y",
    "ebit_change_display_avg_5y",
    "diluted_eps_growth_avg_5y",
    "eps_change_display_avg_5y",
    "eps_ltg_avg_5y",
    "levered_free_cash_flow_yoy_avg_5y",
    "fcf_per_share_change_display_avg_5y",
    "op_cf_yoy_avg_5y",
    "cf_op_change_display_avg_5y",
    "roe_yoy_avg_5y",
    "roe_change_display_avg_5y",
    "working_cap_change_avg_5y",
    "capex_change_avg_5y",
    "dividend_per_share_change_dislpay_avg_5y",
    "dps_yoy_avg_5y",
]

growth_symbol_data_fields = [
    "revenue_growth",
    "revenue_growth3",
    "revenue_growth5",
    "revenueGrowth10",
    "ebitdaYoy",
    "ebitda_3y",
    "ebitda_5y",
    "ebitda_10y",
    "operatingIncomeEbitYoy",
    "operatingIncomeEbit3y",
    "operatingIncomeEbit5y",
    "operatingIncomeEbit10y",
    "netIncomeYoy",
    "netIncome3y",
    "netIncome5y",
    "netIncome10y",
    "normalizedNetIncomeYoy",
    "normalizedNetIncome3y",
    "normalizedNetIncome5y",
    "normalizedNetIncome10y",
    "earningsGrowth",
    "earningsGrowth3",
    "earningsGrowth5y",
    "earningsGrowth10y",
    "dilutedEpsGrowth",
    "dilutedEps3y",
    "dilutedEps5y",
    "dilutedEps10y",
    "tangibleBookValueYoy",
    "tangibleBookValue3y",
    "tangibleBookValue5y",
    "tangibleBookValue10y",
    "totalAssetsYoy",
    "totalAssets3y",
    "totalAssets5y",
    "totalAssets10y",
    "leveredFreeCashFlowYoy",
    "leveredFreeCashFlow3y",
    "leveredFreeCashFlow5y",
    "leveredFreeCashFlow10y",
    "net_interest_income_yoy",
    "net_interest_income_3y",
    "net_interest_income_5y",
    "net_interest_income_10y",
    "gross_loans_yoy",
    "gross_loans_3y",
    "gross_loans_5y",
    "gross_loans_10y",
    "common_equity_yoy",
    "common_equity_3y",
    "common_equity_5y",
    "common_equity_10y",
]

profitability_metrics = [
    "gross_margin",
    "ebit_margin",
    "ebitda_margin",
    "net_margin",
    "levered_fcf_margin",
    "rtn_on_common_equity",
    "return_on_total_capital",
    "return_on_avg_tot_assets",
    "capex_to_sales",
    "assets_turnover",
    "cash_from_operations_as_reported",
    "net_inc_per_employee",
    "gross_margin_avg_5y",
    "ebit_margin_avg_5y",
    "ebitda_margin_avg_5y",
    "net_margin_avg_5y",
    "levered_fcf_margin_avg_5y",
    "rtn_on_common_equity_avg_5y",
    "return_on_total_capital_avg_5y",
    "return_on_avg_tot_assets_avg_5y",
    "capex_to_sales_avg_5y",
    "assets_turnover_avg_5y",
    "cash_from_operations_as_reported_avg_5y",
    "net_inc_per_employee_avg_5y",
]

peers_metrics = [
    "marketcap_display",
    "tev",
    "number_of_employees",
    "authors_count",
    "tot_analysts_recommendations",
    "close",
    "price_high_52w",
    "price_low_52w",
    "p_week_vol_shares",
    "total_return_1m",
    "total_return_3m",
    "total_return_6m",
    "total_return_9m",
    "total_return_ytd",
    "total_return_1y",
    "total_return_3y",
    "total_return_5y",
    "total_return_10y",
    "total_cash",
    "cash_per_share",
    "total_debt",
    "net_debt",
    "debt_eq",
    "debt_short_term",
    "debt_long_term",
    "current_ratio",
    "quick_ratio",
    "interest_coverage_ratio",
    "book_value",
    "debt_fcf",
    "long_term_debt_per_capital",
    "nocf",
    "cash_from_operations_as_reported",
    "levered_free_cash_flow",
    "capital_expenditures",
]

wallstreet_metrics = [
    "authors_rating_strong_buy_count",
    "authors_rating_buy_count",
    "authors_rating_hold_count",
    "authors_rating_sell_count",
    "authors_rating_strong_sell_count",
    "sell_side_rating_strong_buy_count",
    "sell_side_rating_buy_count",
    "sell_side_rating_hold_count",
    "sell_side_rating_sell_count",
    "sell_side_rating_strong_sell_count",
    "authors_rating",
    "sell_side_rating",
]

div_estimate_metrics = [
    "dividends_estimate_fy1_analyst_up_avg_5y",
    "dividends_estimate_fy1_analyst_down_avg_5y",
    "dividends_estimate_fy2_analyst_up_avg_5y",
    "dividends_estimate_fy2_analyst_down_avg_5y",
    "dividends_estimate_fy1_analyst_up",
    "dividends_estimate_fy1_analyst_down",
    "dividends_estimate_fy2_analyst_up",
    "dividends_estimate_fy2_analyst_down",
]

seeking_alpha_all_metrics = {
    "Dividend safety": div_safety_metrics,
    "Dividend growth": div_growth_metrics,
    "Dividend yield": div_yield_metrics,
    "Dividend history": div_history_metrics,
    "Earnings": earnings_metrics,
    "Valuation": valuation_metrics,
    "Growth": growth_metrics + growth_symbol_data_fields,
    "Profitability": profitability_metrics,
    "Wallstreet rating": wallstreet_metrics,
}

radar_categories = seeking_alpha_all_metrics.keys()

stockanalysis_tooltips = {
    "datekey": "Date",
    "revenue": "Revenue",
    "revenueGrowth": "Revenue Growth (YoY)",
    "cor": "Cost of Revenue",
    "gp": "Gross Profit",
    "sgna": "Selling, General & Admin",
    "rnd": "Research & Development",
    "opex": "Operating Expenses",
    "otheropex": "Other Operating Expenses",
    "opinc": "Operating Income",
    "intexp": "Interest Expense / Income",
    "otherincome": "Other Expense / Income",
    "pretax": "Pretax Income",
    "taxexp": "Income Tax",
    "prefdivis": "Preferred Dividends",
    "netinc": "Net Income",
    "netIncomeGrowth": "Net Income Growth (YoY)",
    "shareswa": "Shares Outstanding (Basic)",
    "shareswadil": "Shares Outstanding (Diluted)",
    "sharesYoY": "Shares Change (YoY)",
    "eps": "Earnings Per Share",
    "epsdil": "EPS (Diluted)",
    "epsGrowth": "EPS Growth",
    "fcfps": "Free Cash Flow Per Share",
    "dps": "Dividend Per Share",
    "dividendGrowth": "Dividend Growth (YoY)",
    "fcf": "Free Cash Flow",
    "grossMargin": "Gross Margin",
    "operatingMargin": "Operating Margin",
    "profitMargin": "Profit Margin",
    "fcfMargin": "Free Cash Flow Margin",
    "taxrate": "Effective Tax Rate",
    "ebitda": "EBITDA",
    "ebitdaMargin": "EBITDA Margin",
    "depamor": "Depreciation & Amortization",
    "ebit": "EBIT",
    "ebitMargin": "EBIT Margin",
    "cashneq": "Cash & Equivalents",
    "investmentsc": "Short-Term Investments",
    "totalcash": "Cash & Cash Equivalents",
    "cashGrowth": "Cash Growth (YoY)",
    "receivables": "Receivables",
    "inventory": "Inventory",
    "othercurrent": "Other Current Assets",
    "assetsc": "Total Current Assets",
    "ppnenet": "Property, Plant & Equipment",
    "investmentsnc": "Long-Term Investments",
    "intangibles": "Goodwill and Intangibles",
    "othernoncurrent": "Other Long-Term Assets",
    "assetsnc": "Total Long-Term Assets",
    "assets": "Total Assets",
    "payables": "Accounts Payable",
    "deferredrev": "Deferred Revenue",
    "debtc": "Current Debt",
    "liabilitiesc": "Total Current Liabilities",
    "otherliabilitiescurrent": "Other Current Liabilities",
    "debtnc": "Long-Term Debt",
    "liabilitiesnc": "Total Long-Term Liabilities",
    "otherliabilitiesnoncurrent": "Other Long-Term Liabilities",
    "liabilities": "Total Liabilities",
    "debt": "Total Debt",
    "debtGrowth": "Debt Growth (YoY)",
    "commonstocknet": "Common Stock",
    "retearn": "Retained Earnings",
    "accoci": "Comprehensive Income",
    "equity": "Shareholders' Equity",
    "liabilitiesequity": "Total Liabilities and Equity",
    "netcash": "Net Cash / Debt",
    "netCashGrowth": "Net Cash / Debt Growth (YoY)",
    "netcashpershare": "Net Cash Per Share",
    "workingcapital": "Working Capital",
    "bvps": "Book Value Per Share",
    "sbcomp": "Share-Based Compensation",
    "otheroperating": "Other Operating Activities",
    "ncfo": "Operating Cash Flow",
    "ocfGrowth": "Operating Cash Flow Growth (YoY)",
    "capex": "Capital Expenditures",
    "ncfbus": "Acquisitions",
    "ncfinv": "Change in Investments",
    "otherinvesting": "Other Investing Activities",
    "ncfi": "Investing Cash Flow",
    "ncfdiv": "Dividends Paid",
    "ncfcommon": "Share Issuance / Repurchase",
    "ncfdebt": "Debt Issued / Paid",
    "otherfinancing": "Other Financing Activities",
    "ncff": "Financing Cash Flow",
    "ncf": "Net Cash Flow",
    "fcfGrowth": "Free Cash Flow Growth (YoY)",
    "marketcap": "Market Capitalization",
    "marketCapGrowth": "Market Cap Growth (YoY)",
    "ev": "Enterprise Value",
    "pe": "PE Ratio",
    "ps": "PS Ratio",
    "pb": "PB Ratio",
    "debtequity": "Debt / Equity Ratio",
    "currentratio": "Current Ratio",
    "assetturnover": "Asset Turnover",
    "roe": "Return on Equity (ROE)",
    "roa": "Return on Assets (ROA)",
    "roic": "Return on Capital (ROIC)",
    "dividendyield": "Dividend Yield",
    "payoutratio": "Dividend Payout Ratio",
    "buybackyield": "Buyback Yield / Dilution",
    "totalreturn": "Total Shareholder Return",
}


# https://www.elearnmarkets.com/blog/what-is-stock-rating/
rating_grades_dict = {
    "Buy": "A buy rating is a recommendation for buying a specific stock which implies that analysts are expecting the price of a stock to rise in the short- to mid-term. \
            The analysts are usually of the opinion that the stock can surpass the return of similar stocks in the same sector because of reasons such as the launch of a new product or service.",
    "Sell": "A sell rating is a recommendation for selling a particular stock which means that the analyst is expecting the price of a stock to fall below its current level in tcrehe short or mid-term.\
            A strong sell rating means that analysts are expecting the price of the specific stock to fall significantly below its current level in the near term.\
            If any analysts recommend a strong sell rating on any stock, then a particular company may end up losing its vital business from the company.",
    "Hold": "When an analyst gives a hold rating to stock then they expect it to perform the same with the market or as similar stocks of the same sector.\
            This rating tells the stockbrokers not to buy or sell the stock but to hold.\
            A hold rating is assigned to a stock when there is uncertainty in a company for example regarding new products/services.",
    "Underperform": "An underperform rating means that the company may do slightly worse than the market average or the benchmark index. \
            Thus research analysts recommend the traders stay away from the stock.\
            For example, if a stock's total return is 3% and the Nifty's total return is 6%, then it underperformed the index by 3%.",
    "Outperform": "An outperform rating is assigned to a stock that is projected to provide returns that are higher than the market average or a benchmark index.\
            For example, if a stock's total return is 10% and the Dow Jones Industrial Average's total return is 6%, it has outperformed the index by 4%.",
    "Overweight": "An overweight rating on a stock usually means that it deserves a higher weighting than the benchmark's current weighting for that stock. \
            An overweight rating on a stock means that an equity analyst believes the company's stock price should perform better in the future.",
    "Underweight": "Underweight is a sell or don't buy recommendation that analysts give to specific stocks. \
            It means that they think the stock will perform poorly over the next 12 months. \
            This can mean either losing value or growing slowly, depending on market conditions, but it always means that the analyst believes the stock will underperform its market.",
}
